Bump Pyro and PyTorch dependencies and reinstate VAE
pyro-ppl/funsor pull request #478
Opened 2021-03-04 23:22 UTC by eb8680

Resolves #474

2021-03-04 23:28 UTC, fritzo approved these changes

2021-03-04 23:28 UTC, fritzo commented
Thanks for updating this @eb8680 !

2021-03-04 23:52 UTC, fehiepsi approved these changes

2021-03-05 00:53 UTC, fritzo requested changes
There have been some nontrivial distribution shape changes in PyTorch 1.8 We may need to fix some of the distribution shape conversion.

2021-03-05 00:53 UTC, fritzo commented on .github/workflows/ci.yml
> +        pip install torch==1.8.0+cpu torchvision==0.9.0+cpu -f https://download.pytorch.org/whl/test/cpu/torch_test.html
these should be stable builds

2021-03-05 00:54 UTC, eb8680 commented on .github/workflows/ci.yml
> +        pip install torch==1.8.0+cpu torchvision==0.9.0+cpu -f https://download.pytorch.org/whl/test/cpu/torch_test.html
Tests keep failing with stable builds.

2021-03-05 00:55 UTC, fritzo commented
It looks like you might need to `pip install requests`?

2021-03-05 01:00 UTC, eb8680 commented
> It looks like you might need to pip install requests?

But should we be doing that manually or should it be installed as a dependency of `torchvision`?

2021-03-05 01:05 UTC, eb8680 commented
> We may need to fix some of the distribution shape conversion

The tests in `test_distribution.py` and `test_distribution_generic.py` seem to be passing - are those tests too weak to catch these changes?

2021-03-05 01:07 UTC, eb8680 commented on .github/workflows/ci.yml
> +        pip install torch==1.8.0+cpu torchvision==0.9.0+cpu -f https://download.pytorch.org/whl/test/cpu/torch_test.html
Reverted to stable

2021-03-05 01:26 UTC, fritzo approved these changes
LGTM, thanks for figuring this out

2021-03-05 01:30 UTC, fritzo commented
> should we be [installing requests] manually

I think you probably did the right thing in adding `requests` as a test dependency. In an ideal world we could rely on packages declaring all their dependencies, but honestly the dark corners of Pyro have a few undeclared dependencies (biopython, lap, gpytorch), so I can't criticize.

> are [our existing distribution] tests too weak to catch these changes?

hmm, I guess if they pass, then everything is ok 🤷

2021-03-05 01:30 UTC, merged